shell = "nu"

[window]
opacity = 0.95
blur = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[cursor]
blink_interval = 500
blink_timeout = 5
[cursor.style]
blinking = "On"
shape = "Beam"
